name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      - name: Helm Repos
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add presslabs https://presslabs.github.io/charts
          helm repo add raphaelmonrouzeau https://raphaelmonrouzeau.github.io/charts/repository/
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add bitpoke https://helm-charts.bitpoke.io

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Generate index.html
        run: |
          go install github.com/halkeye/helm-repo-html@v0.0.8
          /home/runner/go/bin/helm-repo-html

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update index.html"
